// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace extensibility_logs_64_bit
{
    internal sealed partial class Vsix
    {
        public const string Id = "extensibility_logs_64_bit.87a34d24-fb47-413e-b273-e9aa0a0fab5b";
        public const string Name = "extensibility_logs_64_bit";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Tim Heuer";
        public const string Tags = "";
    }
}
